services:
  - type: web
    name: odoo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromService:
          type: postgres
          name: odoo-db
      - key: DB_USER
        fromService:
          type: postgres
          name: odoo-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: odoo-db
          property: password

databases:
  - name: odoo-db
    plan: free
    postgresMajorVersion: 15